### ISSUE TITLE
DXF for integrated vat parts?

### ISSUE THREAD

**Issue by mhv-shared** [goopyplastic/littlerp2#1]
Hi, is it possible for you to post the dxf files for the foam insert and FEP film parts shown in the integrated vat build guide?

Also, is there any documentation on the usage of the "hightension" vat parts?

Thanks!

**Comment by davidfanner** [comment]
I would be surprised if that happened, seeing as Flexvat is owned by a
different guy..


Regards
David - 083 279 0286

**Comment by mhv-shared** [comment]
I think it was probably just an oversight. Anyway, if someone else is looking for them, I've added versions to [my fork](https://github.com/mhv-shared/littlerp2/commit/504366068896fd42e6644972d1c0bf598e1bb739)

**Comment by goopyplastic** [comment]
Yes just an oversight, I will get them up. The regular (non expanded) vat is compatible with HTL's films / foams and he has some DXF's online also. I have been meaning to do a high tension video / explanation. I never actually shipped kits with the hightension, it is more just an option if it was needed. You can see the consruction here: http://imgur.com/a/afo7p

The LittleRP2 vat is meant to be run at a fairly low tension, this is to decrease the separation forces (at the cost of film life) we can do this primarily because there is an acrylic window underneath the film. If you wanted to run a window with the central portion open, or needed the film to be at a higher tension for durability reasons then the stock mid plate would start to bow.

The high tension parts basically convert the LittleRP2 vat into a more standard flexvat where the tensioner is part of the vat and the vat is tensioned as a separate unit. Because there is perimeter clamping, you can run higher tension without bowing. You would use different material thicknesses of the tensionstops / windowspacers to achieve different pre-determined tension values (window heights). Using different combinations of 1.5 / 2.5 / 3.0 mm tensionstops / windowspacers you can raise the effect window height in pretty small increments.

These options are also meant as somewhat of a future-proofing, in case the flexvat.com V5 flexvat and seemecnc diy flexvat were no longer offered.

**Comment by goopyplastic** [comment]
I have uploaded these files now.
